# Generated by Django 4.1.4 on 2022-12-18 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouts',
            name='exercise',
        ),
        migrations.AddField(
            model_name='exercises',
            name='workouts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness_app.workouts'),
        ),
    ]
