# Generated by Django 4.1.4 on 2022-12-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0002_remove_workouts_exercise_exercises_workouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
