# Generated by Django 4.1.4 on 2022-12-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0003_exercises_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
