# Generated by Django 4.1.4 on 2022-12-21 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0006_alter_spotifytoken_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotifyToken',
        ),
    ]
