# Generated by Django 4.1.4 on 2022-12-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0007_delete_spotifytoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='date_completed',
            field=models.DateField(null=True),
        ),
    ]
